export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const USER_ADD = "USER_ADD";
export const USER_UPDATE = "USER_UPDATE";

export const TOKEN_ADD = "TOKEN_ADD";
export const TOKEN_UPDATE = "TOKEN_UPDATE";
export const GET_TOTAL_INFO = "GET_TOTAL_INFO";
export const GET_CURRENT_PRICE = "GET_CURRENT_PRICE";
export const GET_CURRENT_AUTHORIZE = "GET_CURRENT_AUTHORIZE"